### ISSUE TITLE
Implement more Data Structures and Algorithms

### ISSUE THREAD

**Issue by SparshBohra** [SparshBohra/C-DSA-Library#1]
### Description

Implement more Data Structures and Algorithms in C and add them to the dsa.h header file. Currently, the file only contains commonly used sorting and searching algorithms and basic data structures.

### Tasks
- [ ] Implement the DS/A in C (Please comment your code)
- [ ] Add it to the dsa.h file 
- [ ] Add the DS/A name to the index at the top
- [ ] Help with documentation is always welcomed
